name: android tools image build and push

on: workflow_dispatch

jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: login to github Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./docker-images-android/sdk/tools/Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}/android-tools:jdk17
